{
    'name': 'Gestión de Clientes de Internet',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Clientes, planes, facturación mensual y cortes automáticos.',
    'author': 'Nathaly García',
    'website': 'https://www.allygo.dev',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/plan_data.xml',
        'data/cron_jobs.xml',
        'views/plan_views.xml',
        'views/client_views.xml',
        'views/invoice_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
