{
    'name': 'Gestión de Clientes de Internet',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Clientes, planes, facturación mensual y cortes automáticos.',
    'author': 'Nathaly García',
    'website': 'https://www.allygo.dev',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/contract_sequence.xml',
        'data/survey_sequence.xml',
        'data/new_sequences.xml',
        'data/plan_data.xml',
        'data/cron_jobs.xml',
        'views/plan_views.xml',
        'views/client_views.xml',
        'views/invoice_views.xml',
        'views/invoice_qweb_template.xml',
        'views/contract_views.xml',
        'views/survey_views.xml',
        'views/instalacion_views.xml',
        'views/tickets_views.xml',
        'views/pagos_views.xml',
        'views/aviso_cobro_views.xml',
        'views/equipo_extra_views.xml',
        'views/onu_views.xml',
        'views/rango_ip_views.xml',
        'views/puerto_views.xml',
        
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    # Assets section removed temporarily to fix loading issues

}
